version: '3'
services: 
  remote_nodejs: 
    container_name: nodejs_container
    image: nodejs_image
    build: 
     context: .
     dockerfile: dockerfile.dev
    ports:
        - "3000:3000"
    volumes: 
        - ".:/app"     

