version: '3'
services: 

#  jenkins: 
#    container_name: my_jenkins
#    image: my_jenkins
#    ports: 
#        - "8080:8080"
#    volumes:
#        - "/home/ahmed/jenkins/jenkins_home:/var/jenkins_home" 
#    networks: 
#        - net


  remote_nodejs: 
    container_name: remote_js_server
    image: node:16-alpine
    build: 
     context: /home/ahmed/nodejs_web/frontend2/
    ports:
        - "3000:3000"
    volumes:
        - "/home/ahmed/nodejs_web/frontend2:/app"     
    networks: 
        - net  

networks: 
    net: 
