version: '3'
services: 
  remote_nodejs: 
    container_name: remote_js
    image: node:16-alpine
    build: 
     context: .
     dockerfile: dockerfile.dev
    ports:
        - "3000:3000"
    volumes: 
        - ".:/app"     

